specVersion: 0.0.4
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  # - name: CdpManager
  #   kind: ethereum/contract
  #   network: goerli
  #   source:
  #     address: "0x11676296549bccF5cA978f8c2b0de913AbE7d01f"
  #     abi: CdpManager
  #     startBlock: 9064557
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities: []
  #     abis:
  #       - name: CdpManager
  #         file: ./abis/CdpManager.json
  #     eventHandlers:
  #       - event: CdpUpdated(indexed address,uint256,uint256,uint256,uint8)
  #         handler: handleCdpUpdated
  #       - event: Redemption(uint256,uint256,uint256,uint256)
  #         handler: handleRedemption
  #       - event: TroveLiquidated(indexed address,uint256,uint256,uint8)
  #         handler: handleTroveLiquidated
  #       - event: Liquidation(uint256,uint256,uint256,uint256)
  #         handler: handleLiquidation
  #         receipt: true
  #     file: ./src/mapping/CdpManager.ts
  # - name: BorrowerOperations
  #   kind: ethereum/contract
  #   network: goerli
  #   source:
  #     address: "0x3b4b99e75a6AeA3111f09b13359951069b0CFF8B"
  #     abi: BorrowerOperations
  #     startBlock: 9064599
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities: []
  #     abis:
  #       - name: BorrowerOperations
  #         file: ./abis/BorrowerOperations.json
  #     eventHandlers:
  #       - event: LUSDBorrowingFeePaid(indexed address,uint256)
  #         handler: handleLUSDBorrowingFeePaid
  #       - event: CdpUpdated(indexed address,uint256,uint256,uint256,uint8)
  #         handler: handleCdpUpdated
  #     file: ./src/mapping/BorrowerOperations.ts
  - name: PriceFeed
    kind: ethereum/contract
    network: goerli
    source:
      abi: PriceFeed
      address: "0xA80553090a2D40796b9E5DFC7c356a9bb1463Ed9"
      startBlock: 9064622
    mapping:
      file: ./src/mapping/PriceFeed.ts
      language: wasm/assemblyscript
      kind: ethereum/events
      apiVersion: 0.0.7
      entities:
        - Token
      abis:
        - name: PriceFeed
          file: ./abis/PriceFeed.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: LastGoodPriceUpdated(uint256)
          handler: handleLastGoodPriceUpdated
  # - name: ActivePool
  #   kind: ethereum/contract
  #   network: goerli
  #   source:
  #     address: "0x04ae82bAbE55907Ce71bE5beB406635670315401"
  #     abi: ActivePool
  #     startBlock: 9064630
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities: []
  #     abis:
  #       - name: ActivePool
  #         file: ./abis/ActivePool.json
  #     eventHandlers:
  #       - event: ActivePoolCollBalanceUpdated(uint256)
  #         handler: handleActivePoolCollBalanceUpdated
  #       - event: ActivePoolEBTCDebtUpdated(uint256)
  #         handler: handleActivePoolEBTCDebtUpdated
  #     file: ./src/mapping/ActivePool.ts
  # - name: CollSurplusPool
  #   kind: ethereum/contract
  #   network: goerli
  #   source:
  #     address: "0xC1B5fE891Be874BB15e8F34B43843D7dFfC55123"
  #     abi: CollSurplusPool
  #     startBlock: 9064639
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities: []
  #     abis:
  #       - name: CollSurplusPool
  #         file: ./abis/CollSurplusPool.json
  #     eventHandlers:
  #       - event: CollBalanceUpdated(indexed address,uint256)
  #         handler: handleCollBalanceUpdated
  #     file: ./src/mapping/CollSurplusPool.ts
